#!/bin/sh
#
# chkconfig: 2345 96 10
# description: kronometrix auth data analytics platform
# 
# /etc/init.d/kauth
#
#BSD 3-Clause License
#
#Copyright (c) 2018, SDR Dynamics, Stefan Parvu
#All rights reserved.
#
#Redistribution and use in source and binary forms, with or without
#modification, are permitted provided that the following conditions are met:
#
#* Redistributions of source code must retain the above copyright notice, this
#  list of conditions and the following disclaimer.
#
#* Redistributions in binary form must reproduce the above copyright notice,
#  this list of conditions and the following disclaimer in the documentation
#  and/or other materials provided with the distribution.
#
#* Neither the name of the copyright holder nor the names of its
#  contributors may be used to endorse or promote products derived from
#  this software without specific prior written permission.
#
#THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
#FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
#SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
#CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

RETVAL=0
OS_NAME=`uname -s`

BASEDIR="/opt/kronometrix/auth/etc"
AUTH_HTTP="${BASEDIR}/http"
AUTH_DB="${BASEDIR}/db"
KRMX_USER="krmx"

# basedir test
test -d ${BASEDIR} || exit 0
test -f ${AUTH_HTTP} || exit 0
test -f ${AUTH_DB} || exit 0


start() {
    su - $KRMX_USER -c "${AUTH_DB} start >/dev/null 2>&1"
    sleep 1
    su - $KRMX_USER -c "${AUTH_HTTP} start >/dev/null 2>&1"
}


stop() {
    su - $KRMX_USER -c "${AUTH_HTTP} stop >/dev/null 2>&1"
    sleep 1
    su - $KRMX_USER -c "${AUTH_DB} stop >/dev/null 2>&1"
}


case "$1" in
   start)
      start
      ;;
   stop)
      stop
      ;;
   restart)
      stop
      start
      ;;
   *)
      echo "Usage: $0 {start|stop|restart}"
      exit 1
esac
exit $RETVAL
