#!/bin/sh

#BSD 3-Clause License
#
#Copyright (c) 2018, SDR Dynamics, Stefan Parvu
#All rights reserved.
#
#Redistribution and use in source and binary forms, with or without
#modification, are permitted provided that the following conditions are met:
#
#* Redistributions of source code must retain the above copyright notice, this
#  list of conditions and the following disclaimer.
#
#* Redistributions in binary form must reproduce the above copyright notice,
#  this list of conditions and the following disclaimer in the documentation
#  and/or other materials provided with the distribution.
#
#* Neither the name of the copyright holder nor the names of its
#  contributors may be used to endorse or promote products derived from
#  this software without specific prior written permission.
#
#THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
#FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
#SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
#CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

RETVAL=0
OS_NAME=`uname -s`

BASEDIR="/opt/kronometrix/auth"
HTTP_CMD="${BASEDIR}/nginx/sbin/nginx"
HTTP_CONF="${BASEDIR}/nginx/conf/nginx.conf"
HTTP_PID="${BASEDIR}/nginx/logs/nginx.pid"

# basedir test
test -d ${BASEDIR} || exit 0


start() {
    echo "Starting Kronometrix auth http service"

    if [ "X${OS_NAME}" = "XSunOS" ]; then
        echo " ${rep} service: \c"
    else
        echo -n " ${rep} service: "
    fi  

    if [ -f ${HTTP_PID} ]; then
        kill -0 `cat ${HTTP_PID}` >/dev/null 2>&1
        if [ $? -eq  1 ]; then
            rm ${HTTP_PID}
            $HTTP_CMD -c $HTTP_CONF &
            RETVAL=$?
        else
            RETVAL=1
        fi
    else
        $HTTP_CMD -c $HTTP_CONF 2>/dev/null &
        RETVAL=$?
    fi

    [ $RETVAL -eq 0 ] && echo "ok" || echo "failed"

    return $RETVAL
}


stop() {
    echo "Stopping Kronometrix auth service"

    if [ "X${OS_NAME}" = "XSunOS" ]; then
        echo " ${rep} service: \c"
    else
        echo -n " ${rep} service: "
    fi

    if [ -f ${HTTP_PID} ]; then
        kill `cat ${HTTP_PID}` >/dev/null 2>&1
        RETVAL=$?
        [ $RETVAL -eq 0 ] && echo "ok" || echo "failed"
    else
        RETVAL=1
        [ $RETVAL -eq 0 ] && echo "ok" || echo "failed"
    fi

    return $RETVAL
}


case "$1" in
   start)
      start
      ;;
   stop)
      stop
      ;;
   restart)
      stop 
      sleep 1
      start
      ;;
   *)
      echo "Usage: $0 {start|stop|restart}"
      exit 1
esac
exit $RETVAL
