#!/bin/sh

# The MIT License (MIT)

# Copyright (c) 2015 Kronometrix
# Copyright (c) 2015 SDR Dynamics Oy

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

RETVAL=0
OS_NAME=`uname -s`

BASEDIR="/opt/kronometrix/auth/etc"
AUTH_HTTP="${BASEDIR}/http"
AUTH_DB="${BASEDIR}/db"

# basedir test
test -d ${BASEDIR} || exit 0
test -f ${AUTH_HTTP} || exit 0
test -f ${AUTH_DB} || exit 0


start() {
    ${AUTH_DB} start
    sleep 1
    ${AUTH_HTTP} start
}


stop() {
    ${AUTH_HTTP} stop
    sleep 1
    ${AUTH_DB} stop
}


case "$1" in
   start)
      start
      ;;
   stop)
      stop
      ;;
   restart)
      stop
      start
      ;;
   *)
      echo "Usage: $0 {start|stop|restart}"
      exit 1
esac
exit $RETVAL
