#!/bin/sh

# initial installation, after tasks
chown -R krmx:krmx /opt/kronometrix/auth || :

if [ ! -L /etc/init.d/kronometrix.auth ]; then
    ln -s /opt/kronometrix/auth/etc/kronometrix.auth /etc/init.d/kronometrix.auth || :
fi

# link here kronometrix.auth
update-rc.d kronometrix.auth start 20 2 3 4 5 . stop 20 0 1 6 . >/dev/null 2>&1 || :

if [ -d /opt/kronometrix/auth/logs ]; then
    chown -R krmx:krmx /opt/kronometrix/auth/logs || :
fi

/etc/init.d/kronometrix.auth start >/dev/null 2>&1 || :
