#!/bin/sh

# initial installation, after tasks
chown -R krmx:krmx /opt/kronometrix/auth || :

if [ ! -L /etc/init.d/kauth ]; then
    ln -s /opt/kronometrix/auth/etc/rc/kauth /etc/init.d/kauth || :
fi

# link here kauth
update-rc.d kauth start 20 2 3 4 5 . stop 20 0 1 6 . >/dev/null 2>&1 || :

if [ -d /opt/kronometrix/auth/logs ]; then
    chown -R krmx:krmx /opt/kronometrix/auth/logs || :
fi

/etc/init.d/kauth start >/dev/null 2>&1 || :
