#!/bin/sh

# echo "preinst: preparing to install package"
# initial installation
if [ -f /etc/init.d/kronometrix.auth ]; then
    # echo "preinst: stopping kronometrix auth..."
    su - krmx -c "/etc/init.d/kronometrix.auth stop >/dev/null 2>&1" || :
fi

if ! getent group krmx >/dev/null; then
        groupadd krmx || :
fi

if ! getent passwd krmx >/dev/null; then
    useradd -g krmx -d /home/krmx -m krmx || :
fi

if [ ! -d /opt/kronometrix ]; then
    mkdir /opt/kronometrix || :
fi

