#!/bin/sh

update-rc.d -f kronometrix.auth remove >/dev/null 2>&1 || : 

# uinstall
if [ -L /etc/init.d/kronometrix.auth ]; then
    /etc/init.d/kronometrix.auth stop >/dev/null 2>&1 || :
    rm -f /etc/init.d/kronometrix.auth || :
fi
