#!/bin/sh

if [ $2 == "DEINSTALL" ]; then
    /etc/rc.d/kronometrix_auth onestop >/dev/null 2>&1
fi

if [ $2 == "POST-DEINSTALL" ]; then
    [ -f /etc/rc.d/kronometrix_auth ] && rm /etc/rc.d/kronometrix_auth
fi
